repo sync -cd --no-tags -j2 ruby/platform/prebuilts/qemu-kernel
repo sync -cd --no-tags -j2 ruby/platform/external/avahi
repo sync -cd --no-tags -j2 ruby/platform/external/harfbuzz_ng
repo sync -cd --no-tags -j2 ruby/platform/external/icu
repo sync -cd --no-tags -j2 ruby/platform/external/tagsoup
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvOta
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/vcard
repo sync -cd --no-tags -j2 ruby/kernel/lk
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Camera2
repo sync -cd --no-tags -j2 mtk_pre_cta/platform/vendor/letv/packages/LetvThemeSettings
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/go/linux-x86
repo sync -cd --no-tags -j2 ruby/platform/external/eyes-free
repo sync -cd --no-tags -j2 ruby/device/generic/qemu
repo sync -cd --no-tags -j2 ruby/platform/external/jcommander
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/hwconfig
repo sync -cd --no-tags -j2 ruby/device/generic/mini-emulator-arm64
repo sync -cd --no-tags -j2 ruby/platform/external/mdnsresponder
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/preloadapps/gapps
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/SnapdragonGallery
repo sync -cd --no-tags -j2 ruby/platform/packages/inputmethods/OpenWnn
repo sync -cd --no-tags -j2 ruby/platform/packages/experimental
repo sync -cd --no-tags -j2 ruby/platform/frameworks/compile/libbcc
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/emoji
repo sync -cd --no-tags -j2 ruby/platform/vendor/nxp/opensource/frameworks
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.11-4.8
repo sync -cd --no-tags -j2 ruby/platform/packages/screensavers/PhotoTable
repo sync -cd --no-tags -j2 ruby/platform/external/google-fonts/coming-soon
repo sync -cd --no-tags -j2 ruby/platform/external/piex
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/bluetooth
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/Launcher3
repo sync -cd --no-tags -j2 ruby/platform/external/libopus
repo sync -cd --no-tags -j2 ruby/platform/hardware/qcom/display
repo sync -cd --no-tags -j2 ruby/platform/external/libutf
repo sync -cd --no-tags -j2 ruby/platform/build
repo sync -cd --no-tags -j2 ruby/platform/tools/external/fat32lib
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/SpeechRecorder
repo sync -cd --no-tags -j2 ruby/platform/external/libese-spi
repo sync -cd --no-tags -j2 ruby/platform/external/google-fonts/cutive-mono
repo sync -cd --no-tags -j2 ruby/platform/external/guava
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvPowerController
repo sync -cd --no-tags -j2 ruby/platform/tools/external/gradle
repo sync -cd --no-tags -j2 ruby/platform/external/okhttp
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvCalendarImporter
repo sync -cd --no-tags -j2 ruby/platform/external/dexmaker
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/offlinelog
repo sync -cd --no-tags -j2 ruby/platform/external/libhevc
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvBackupClient
repo sync -cd --no-tags -j2 ruby/platform/hardware/invensense
repo sync -cd --no-tags -j2 ruby/platform/frameworks/wilhelm
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/ninja/linux-x86
repo sync -cd --no-tags -j2 ruby/platform/external/libusb-compat
repo sync -cd --no-tags -j2 ruby/platform/build/soong
repo sync -cd --no-tags -j2 ruby/platform/external/antlr
repo sync -cd --no-tags -j2 ruby/platform/external/wpa_supplicant_8
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvSystemUi
repo sync -cd --no-tags -j2 ruby/platform/frameworks/webview
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Launcher2
repo sync -cd --no-tags -j2 ruby/platform/external/androidplot
repo sync -cd --no-tags -j2 ruby/platform/external/libedit
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Settings
repo sync -cd --no-tags -j2 ruby/platform/external/libmtp
repo sync -cd --no-tags -j2 ruby/platform/external/mksh
repo sync -cd --no-tags -j2 ruby/platform/external/clang
repo sync -cd --no-tags -j2 ruby/platform/external/libusb
repo sync -cd --no-tags -j2 ruby/platform/external/modp_b64
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/fst-manager
repo sync -cd --no-tags -j2 ruby/platform/dalvik
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/libs/libedit
repo sync -cd --no-tags -j2 ruby/platform/external/bzip2
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/bitmap
repo sync -cd --no-tags -j2 ruby/platform/hardware/qcom/wlan
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/common
repo sync -cd --no-tags -j2 ruby/platform/external/jsr305
repo sync -cd --no-tags -j2 ruby/platform/external/libvorbis
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/preloadapps/eui
repo sync -cd --no-tags -j2 ruby/platform/external/donuts
repo sync -cd --no-tags -j2 ruby/platform/external/skia
repo sync -cd --no-tags -j2 ruby/platform/external/libnfc-nxp
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Mms
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gcc/darwin-x86/arm/arm-eabi-4.8
repo sync -cd --no-tags -j2 ruby/platform/external/protobuf
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/calendar
repo sync -cd --no-tags -j2 ruby/platform/system/media
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvSafe
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/fm
repo sync -cd --no-tags -j2 ruby/device/google/contexthub
repo sync -cd --no-tags -j2 ruby/platform/external/ant-wireless/ant_service
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/BasicSmsReceiver
repo sync -cd --no-tags -j2 ruby/platform/external/libnfnetlink
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvEmojiStore
repo sync -cd --no-tags -j2 ruby/platform/external/doclava
repo sync -cd --no-tags -j2 ruby/platform/external/deqp
repo sync -cd --no-tags -j2 ruby/platform/external/rootdev
repo sync -cd --no-tags -j2 ruby/platform/external/ksoap2
repo sync -cd --no-tags -j2 ruby/platform/external/libchrome
repo sync -cd --no-tags -j2 ruby/platform/external/jsr330
repo sync -cd --no-tags -j2 ruby/platform/external/zxing
repo sync -cd --no-tags -j2 ruby/platform/vendor/paragon/ufsd
repo sync -cd --no-tags -j2 ruby/platform/external/iproute2
repo sync -cd --no-tags -j2 ruby/platform/external/libweave
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/KeyChain
repo sync -cd --no-tags -j2 ruby/platform/external/libjpeg-turbo
repo sync -cd --no-tags -j2 ruby/platform/external/dhcpcd-6.8.2
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/dolby
repo sync -cd --no-tags -j2 ruby/platform/external/robolectric
repo sync -cd --no-tags -j2 ruby/platform/system/security
repo sync -cd --no-tags -j2 ruby/platform/external/mockftpserver
repo sync -cd --no-tags -j2 ruby/platform/external/chromium-libpac
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/timezonepicker
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/camera
repo sync -cd --no-tags -j2 ruby/platform/external/google-tv-pairing-protocol
repo sync -cd --no-tags -j2 ruby/platform/external/nanopb-c
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/inputmethodcommon
repo sync -cd --no-tags -j2 ruby/platform/packages/services/Telecomm
repo sync -cd --no-tags -j2 ruby/platform/external/emma
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/SpareParts
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/LeArping
repo sync -cd --no-tags -j2 ruby/platform/external/libvpx
repo sync -cd --no-tags -j2 ruby/platform/platform_testing
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Nfc
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/FMRadio
repo sync -cd --no-tags -j2 ruby/platform/external/libgsm
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvShareProvider
repo sync -cd --no-tags -j2 ruby/platform/external/parameter-framework
repo sync -cd --no-tags -j2 ruby/platform/system/ca-certificates
repo sync -cd --no-tags -j2 ruby/platform/vendor/nxp/opensource/external/libnfc-nci
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvCellBroadcastReceiver
repo sync -cd --no-tags -j2 ruby/device/generic/x86
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/mmc-utils
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/CertInstaller
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/clang/linux-x86/host/3.6
repo sync -cd --no-tags -j2 ruby/platform/external/libvterm
repo sync -cd --no-tags -j2 ruby/platform/frameworks/compile/mclinker
repo sync -cd --no-tags -j2 ruby/platform/system/core
repo sync -cd --no-tags -j2 ruby/platform/development
repo sync -cd --no-tags -j2 msm8996/AMSS/cpe_proc
repo sync -cd --no-tags -j2 ruby/platform/external/google-fonts/carrois-gothic-sc
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LeDomain
repo sync -cd --no-tags -j2 msm8996/AMSS/cnss_proc
repo sync -cd --no-tags -j2 ruby/platform/external/libpcap
repo sync -cd --no-tags -j2 ruby/platform/external/libdrm
repo sync -cd --no-tags -j2 ruby/platform/external/iw
repo sync -cd --no-tags -j2 ruby/platform/packages/providers/UserDictionaryProvider
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/net/ims
repo sync -cd --no-tags -j2 ruby/platform/external/chromium-trace
repo sync -cd --no-tags -j2 ruby/platform/external/hyphenation-patterns
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvSmartLock
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/rcs-service
repo sync -cd --no-tags -j2 ruby/platform/external/xmp_toolkit
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvFreeFlow
repo sync -cd --no-tags -j2 ruby/platform/external/compiler-rt
repo sync -cd --no-tags -j2 ruby/platform/external/gemmlowp
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/wlan/prima
repo sync -cd --no-tags -j2 ruby/platform/external/tinycompress
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/bluetooth
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/SmartCardService
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom/thorium_32
repo sync -cd --no-tags -j2 ruby/platform/external/curl
repo sync -cd --no-tags -j2 ruby/platform/external/android-clat
repo sync -cd --no-tags -j2 ruby/platform/abi/cpp
repo sync -cd --no-tags -j2 ruby/device/common
repo sync -cd --no-tags -j2 ruby/platform/external/blktrace
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/shortcut-fe
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/tools
repo sync -cd --no-tags -j2 ruby/platform/external/naver-fonts
repo sync -cd --no-tags -j2 ruby/platform/packages/providers/ApplicationsProvider
repo sync -cd --no-tags -j2 ruby/platform/external/libnetfilter_conntrack
repo sync -cd --no-tags -j2 ruby/platform/external/dlmalloc
repo sync -cd --no-tags -j2 ruby/platform/external/shflags
repo sync -cd --no-tags -j2 ruby/platform/external/nanohttpd
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/prebuilt
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/utils
repo sync -cd --no-tags -j2 ruby/platform/external/kernel-headers
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/wlan
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/letvfingerprintex
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9
repo sync -cd --no-tags -j2 ruby/platform/bootable/recovery
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom/thorium_64
repo sync -cd --no-tags -j2 ruby/platform/external/libmpeg2
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/LegacyCamera
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvAccountInfo
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/preloadapps/scripts
repo sync -cd --no-tags -j2 ruby/platform/external/sl4a
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/chips
repo sync -cd --no-tags -j2 ruby/platform/external/caliper
repo sync -cd --no-tags -j2 ruby/platform/packages/providers/TelephonyProvider
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/libfurion
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/TV
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/OneTimeInitializer
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/Gallery2
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvMonitor
repo sync -cd --no-tags -j2 ruby/platform/external/libunwind
repo sync -cd --no-tags -j2 ruby/platform/external/timezonepicker-support
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/packages/NfcNxp/LTSMClient
repo sync -cd --no-tags -j2 ruby/platform/external/junit
repo sync -cd --no-tags -j2 ruby/platform/external/jetty
repo sync -cd --no-tags -j2 ruby/platform/external/zlib
repo sync -cd --no-tags -j2 ruby/platform/external/dnsmasq
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9
repo sync -cd --no-tags -j2 ruby/platform/frameworks/data-binding
repo sync -cd --no-tags -j2 ruby/device/generic/armv7-a-neon
repo sync -cd --no-tags -j2 ruby/platform/external/proguard
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/UnifiedEmail
repo sync -cd --no-tags -j2 ruby/platform/external/libcap
repo sync -cd --no-tags -j2 ruby/device/generic/arm64
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/sepolicy
repo sync -cd --no-tags -j2 ruby/platform/external/archive-patcher
repo sync -cd --no-tags -j2 ruby/platform/external/nfacct
repo sync -cd --no-tags -j2 leui_lollipop/platform/external/tinyproxy
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvEuiTransfer
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/providers/LetvMmsProvider
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvCompass
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/ExactCalculator
repo sync -cd --no-tags -j2 ruby/platform/external/nist-sip
repo sync -cd --no-tags -j2 ruby/platform/frameworks/minikin
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvPrivacyData
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvFileManager
repo sync -cd --no-tags -j2 ruby/platform/external/f2fs-tools
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/CMFileManager
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvAccountAgent
repo sync -cd --no-tags -j2 ruby/platform/external/gmock
repo sync -cd --no-tags -j2 ruby/platform/hardware/libhardware
repo sync -cd --no-tags -j2 ruby/platform/packages/providers/CallLogProvider
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/telephony
repo sync -cd --no-tags -j2 ruby/platform/bionic
repo sync -cd --no-tags -j2 ruby/platform/external/mm-dash
repo sync -cd --no-tags -j2 ruby/platform/frameworks/base
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/qcom_amss
repo sync -cd --no-tags -j2 ruby/platform/frameworks/av
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/wlan/utils/sigma-dut
repo sync -cd --no-tags -j2 ruby/platform/system/connectivity/dhcp_client
repo sync -cd --no-tags -j2 ruby/platform/external/gtest
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/overlay
repo sync -cd --no-tags -j2 ruby/platform/system/bt
repo sync -cd --no-tags -j2 ruby/platform/build/kati
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvBackupService
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/QuickSearchBox
repo sync -cd --no-tags -j2 ruby/platform/packages/providers/PartnerBookmarksProvider
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/Calendar
repo sync -cd --no-tags -j2 ruby/device/generic/mini-emulator-x86_64
repo sync -cd --no-tags -j2 ruby/platform/external/libdivsufsort
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/SafetyRegulatoryInfo
repo sync -cd --no-tags -j2 ruby/platform/system/nvram
repo sync -cd --no-tags -j2 ruby/platform/external/tinyalsa
repo sync -cd --no-tags -j2 tools/repo
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/preloadapps/gms
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/frameworks
repo sync -cd --no-tags -j2 msm8996/AMSS/trustzone_images
repo sync -cd --no-tags -j2 ruby/platform/external/nist-pkits
repo sync -cd --no-tags -j2 ruby/platform/external/speex
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/photoviewer
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/yep-qmi
repo sync -cd --no-tags -j2 ruby/platform/external/jacoco
repo sync -cd --no-tags -j2 ruby/platform/external/easymock
repo sync -cd --no-tags -j2 ruby/platform/system/sepolicy
repo sync -cd --no-tags -j2 ruby/platform/external/sonivox
repo sync -cd --no-tags -j2 ruby/platform/art
repo sync -cd --no-tags -j2 ruby/platform/external/regex-re2
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/maven_repo/android
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/StorageManager
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/dataservices
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvRoaming
repo sync -cd --no-tags -j2 ruby/platform/hardware/qcom/bootctrl
repo sync -cd --no-tags -j2 ruby/platform/external/minijail
repo sync -cd --no-tags -j2 ruby/platform/external/webp
repo sync -cd --no-tags -j2 letv/platform/packages/providers/LetvYellowpageProvider
repo sync -cd --no-tags -j2 letv/platform/packages/apps/LetvCloudService
repo sync -cd --no-tags -j2 msm8996/platform/vendor/qcom/proprietary2
repo sync -cd --no-tags -j2 ruby/platform/external/oauth
repo sync -cd --no-tags -j2 ruby/platform/external/selinux
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/fctest
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gdb/linux-x86
repo sync -cd --no-tags -j2 ruby/platform/system/extras
repo sync -cd --no-tags -j2 ruby/platform/external/tinyxml2
repo sync -cd --no-tags -j2 ruby/platform/external/eclipse-windowbuilder
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/deqp
repo sync -cd --no-tags -j2 ruby/platform/hardware/google/apf
repo sync -cd --no-tags -j2 ruby/platform/external/markdown
repo sync -cd --no-tags -j2 msm8994/platform/vendor/letv/LetvCamera
repo sync -cd --no-tags -j2 ruby/platform/external/libphonenumber
repo sync -cd --no-tags -j2 ruby/platform/external/tremolo
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/net/voip
repo sync -cd --no-tags -j2 ruby/platform/external/bison
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvBugServices
repo sync -cd --no-tags -j2 ruby/device/generic/mini-emulator-armv7-a-neon
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/sdk
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Protips
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/preloadapps/cmcc
repo sync -cd --no-tags -j2 ruby/platform/external/aac
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvSystemReport
repo sync -cd --no-tags -j2 ruby/platform/external/roboto-fonts
repo sync -cd --no-tags -j2 msm8996/AMSS/btfm_proc
repo sync -cd --no-tags -j2 ruby/platform/external/google-breakpad
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/colorpicker
repo sync -cd --no-tags -j2 ruby/platform/external/hamcrest
repo sync -cd --no-tags -j2 ruby/platform/external/unicode
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/diag/yepdiag
repo sync -cd --no-tags -j2 ruby/platform/external/crcalc
repo sync -cd --no-tags -j2 ruby/platform/system/connectivity/shill
repo sync -cd --no-tags -j2 ruby/platform/external/opencv
repo sync -cd --no-tags -j2 ruby/platform/external/esd
repo sync -cd --no-tags -j2 ruby/platform/external/eclipse-basebuilder
repo sync -cd --no-tags -j2 ruby/platform/external/webrtc
repo sync -cd --no-tags -j2 ruby/platform/external/zopfli
repo sync -cd --no-tags -j2 ruby/platform/hardware/qcom/media
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/ContactsCommon
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvPhoneControl
repo sync -cd --no-tags -j2 ruby/platform/external/flac
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/DeskClock
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/securemsm
repo sync -cd --no-tags -j2 ruby/platform/system/connectivity/apmanager
repo sync -cd --no-tags -j2 ruby/platform/system/tools/aidl
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvUsageStatsReporter
repo sync -cd --no-tags -j2 ruby/platform/tools/test/connectivity
repo sync -cd --no-tags -j2 ruby/platform/external/libvncserver
repo sync -cd --no-tags -j2 ruby/platform/external/liblzf
repo sync -cd --no-tags -j2 ruby/platform/external/mp4parser
repo sync -cd --no-tags -j2 ruby/platform/external/javasqlite
repo sync -cd --no-tags -j2 msm8996/AMSS/adsp_proc
repo sync -cd --no-tags -j2 ruby/platform/external/mockito
repo sync -cd --no-tags -j2 ruby/platform/external/jsmn
repo sync -cd --no-tags -j2 ruby/platform/external/jsilver
repo sync -cd --no-tags -j2 ruby/platform/external/guice
repo sync -cd --no-tags -j2 ruby/platform/external/libunwind_llvm
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvMusic
repo sync -cd --no-tags -j2 ruby/platform/system/weaved
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/charge_logger
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LeWidget
repo sync -cd --no-tags -j2 ruby/platform/external/lzma
repo sync -cd --no-tags -j2 ruby/platform/packages/screensavers/WebView
repo sync -cd --no-tags -j2 ruby/platform/external/netcat
repo sync -cd --no-tags -j2 ruby/platform/external/libdaemon
repo sync -cd --no-tags -j2 ruby/platform/external/bouncycastle
repo sync -cd --no-tags -j2 ruby/platform/external/brctl
repo sync -cd --no-tags -j2 ruby/platform/packages/providers/TvProvider
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/Dialer
repo sync -cd --no-tags -j2 ruby/platform/external/jsoncpp
repo sync -cd --no-tags -j2 ruby/platform/external/srtp
repo sync -cd --no-tags -j2 ruby/platform/external/dbus
repo sync -cd --no-tags -j2 ruby/platform/vendor/nxp/opensource/packages/apps/Nfc
repo sync -cd --no-tags -j2 ruby/platform/frameworks/native
repo sync -cd --no-tags -j2 ruby/platform/external/tcpdump
repo sync -cd --no-tags -j2 ruby/platform/external/fio
repo sync -cd --no-tags -j2 ruby/platform/external/freetype
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/Calculator
repo sync -cd --no-tags -j2 ruby/platform/external/messageformat
repo sync -cd --no-tags -j2 ruby/platform/external/ipsec-tools
repo sync -cd --no-tags -j2 ruby/platform/external/cros/system_api
repo sync -cd --no-tags -j2 ruby/platform/external/valgrind
repo sync -cd --no-tags -j2 ruby/platform/system/gatekeeper
repo sync -cd --no-tags -j2 ruby/platform/hardware/ril
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/audio
repo sync -cd --no-tags -j2 ruby/platform/external/boringssl
repo sync -cd --no-tags -j2 ruby/platform/frameworks/ml
repo sync -cd --no-tags -j2 msm8996/AMSS/wigig_proc
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/display
repo sync -cd --no-tags -j2 ruby/platform/external/google-fonts/dancing-script
repo sync -cd --no-tags -j2 ruby/platform/external/universal-tween-engine
repo sync -cd --no-tags -j2 ruby/platform/external/iptables
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/MusicFX
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvAppUpgrade
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvGalleryRefocus
repo sync -cd --no-tags -j2 ruby/platform/external/littlemock
repo sync -cd --no-tags -j2 ruby/platform/packages/providers/BlockedNumberProvider
repo sync -cd --no-tags -j2 ruby/platform/external/p61-jcop-kit
repo sync -cd --no-tags -j2 ruby/platform/external/tinyxml
repo sync -cd --no-tags -j2 ruby/platform/external/ltrace
repo sync -cd --no-tags -j2 ruby/device/generic/goldfish-opengl
repo sync -cd --no-tags -j2 ruby/platform/external/autotest
repo sync -cd --no-tags -j2 ruby/platform/packages/services/Telephony
repo sync -cd --no-tags -j2 ruby/platform/external/squashfs-tools
repo sync -cd --no-tags -j2 ruby/platform/pdk
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/WallpaperPicker
repo sync -cd --no-tags -j2 ruby/kernel/msm-3.18
repo sync -cd --no-tags -j2 ruby/platform/external/ebtables
repo sync -cd --no-tags -j2 ruby/device/generic/mini-emulator-x86
repo sync -cd --no-tags -j2 ruby/platform/external/xmlrpcpp
repo sync -cd --no-tags -j2 ruby/platform/external/libcxx
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Tag
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/dpm
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvUserManual
repo sync -cd --no-tags -j2 ruby/platform/system/qcom
repo sync -cd --no-tags -j2 ruby/platform/external/dng_sdk
repo sync -cd --no-tags -j2 ruby/platform/system/netd
repo sync -cd --no-tags -j2 ruby/platform/frameworks/multidex
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvKeyguard
repo sync -cd --no-tags -j2 ruby/platform/libcore
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/Email
repo sync -cd --no-tags -j2 ruby/platform/external/jarjar
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvYellowpage
repo sync -cd --no-tags -j2 ruby/platform/frameworks/volley
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/InCallUI
repo sync -cd --no-tags -j2 ruby/device/google/accessory/arduino
repo sync -cd --no-tags -j2 ruby/device/google/accessory/demokit
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/PhoneCommon
repo sync -cd --no-tags -j2 ruby/platform/system/webservd
repo sync -cd --no-tags -j2 ruby/platform/external/libogg
repo sync -cd --no-tags -j2 ruby/platform/external/vboot_reference
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/frameworks/media
repo sync -cd --no-tags -j2 ruby/platform/external/libxml2
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom/cobalt
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/HTMLViewer
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LeFidoAsm
repo sync -cd --no-tags -j2 ruby/platform/external/jhead
repo sync -cd --no-tags -j2 ruby/platform/external/libgdx
repo sync -cd --no-tags -j2 ruby/platform/vendor/widevine
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvWallet
repo sync -cd --no-tags -j2 ruby/platform/external/sqlite
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/providers/CalendarProvider
repo sync -cd --no-tags -j2 ruby/platform/packages/screensavers/Basic
repo sync -cd --no-tags -j2 ruby/platform/external/libavc
repo sync -cd --no-tags -j2 ruby/platform/cts
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/SnapdragonLauncher
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/tools
repo sync -cd --no-tags -j2 ruby/platform/hardware/qcom/camera
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvBrowser
repo sync -cd --no-tags -j2 ruby/device/google/atv
repo sync -cd --no-tags -j2 ruby/platform/libnativehelper
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/location
repo sync -cd --no-tags -j2 ruby/platform/external/libnl
repo sync -cd --no-tags -j2 ruby/platform/external/objenesis
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/datetimepicker
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/clang/host/linux-x86
repo sync -cd --no-tags -j2 ruby/device/qcom/common
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/DevCamera
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/Exchange
repo sync -cd --no-tags -j2 ruby/platform/system/update_engine
repo sync -cd --no-tags -j2 ruby/platform/external/vogar
repo sync -cd --no-tags -j2 ruby/platform/external/libbrillo
repo sync -cd --no-tags -j2 ruby/platform/packages/inputmethods/LatinIME
repo sync -cd --no-tags -j2 ruby/platform/external/e2fsprogs_custom
repo sync -cd --no-tags -j2 ruby/platform/frameworks/compile/slang
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/EmergencyInfo
repo sync -cd --no-tags -j2 ruby/platform/external/lld
repo sync -cd --no-tags -j2 ruby/platform/external/jmdns
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/webview
repo sync -cd --no-tags -j2 ruby/platform/external/powertop
repo sync -cd --no-tags -j2 ruby/platform/packages/providers/BookmarkProvider
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvPay
repo sync -cd --no-tags -j2 ruby/platform/packages/services/Mms
repo sync -cd --no-tags -j2 ruby/platform/external/tpm2
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/debug_service
repo sync -cd --no-tags -j2 ruby/platform/external/libevent
repo sync -cd --no-tags -j2 ruby/platform/frameworks/ex
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/providers/ContactsProvider
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/SnapdragonCamera
repo sync -cd --no-tags -j2 ruby/platform/external/libnfc-nci
repo sync -cd --no-tags -j2 ruby/platform/external/eigen
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvPersonalized
repo sync -cd --no-tags -j2 ruby/platform/external/iputils
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Phone
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/kernel/kernel-tests
repo sync -cd --no-tags -j2 ruby/platform/system/tpm
repo sync -cd --no-tags -j2 ruby/platform/external/libselinux
repo sync -cd --no-tags -j2 ruby/platform/frameworks/support
repo sync -cd --no-tags -j2 ruby/platform/external/mesa3d
repo sync -cd --no-tags -j2 ruby/platform/external/giflib
repo sync -cd --no-tags -j2 ruby/platform/external/ant-glob
repo sync -cd --no-tags -j2 ruby/platform/external/scrypt
repo sync -cd --no-tags -j2 ruby/platform/hardware/qcom/gps
repo sync -cd --no-tags -j2 ruby/platform/external/testng
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvSetupWizard
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/preloadapps/cu
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/preloadapps/ct
repo sync -cd --no-tags -j2 ruby/platform/external/mockwebserver
repo sync -cd --no-tags -j2 ruby/platform/external/vulkan-validation-layers
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8
repo sync -cd --no-tags -j2 ruby/platform/external/toybox
repo sync -cd --no-tags -j2 ruby/platform/external/snakeyaml
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/ManagedProvisioning
repo sync -cd --no-tags -j2 msm8996/AMSS/venus_proc
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvHawk
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/setupwizard
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/ffmpeg
repo sync -cd --no-tags -j2 ruby/platform/system/firewalld
repo sync -cd --no-tags -j2 ruby/platform/external/drm_hwcomposer
repo sync -cd --no-tags -j2 ruby/platform/external/c-ares
repo sync -cd --no-tags -j2 ruby/platform/external/cblas
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Gallery
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/le_lepd
repo sync -cd --no-tags -j2 ruby/platform/external/libmicrohttpd
repo sync -cd --no-tags -j2 ruby/platform/external/expat
repo sync -cd --no-tags -j2 ruby/platform/external/strace
repo sync -cd --no-tags -j2 ruby/platform/external/tlsdate
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/build
repo sync -cd --no-tags -j2 ruby/platform/packages/wallpapers/LivePicker
repo sync -cd --no-tags -j2 ruby/platform/hardware/qcom/bt
repo sync -cd --no-tags -j2 ruby/platform/packages/providers/MediaProvider
repo sync -cd --no-tags -j2 ruby/device/generic/x86_64
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Stk
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/QcCrashHandler
repo sync -cd --no-tags -j2 ruby/platform/external/ims
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/CellBroadcastReceiver
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/wihd
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/wlan/qcacld-2.0
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvMms
repo sync -cd --no-tags -j2 ruby/platform/external/replicaisland
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/devtools
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvWallpaperSettings
repo sync -cd --no-tags -j2 ruby/platform/external/google-benchmark
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/libblurengine
repo sync -cd --no-tags -j2 ruby/platform/external/elfutils
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/tools
repo sync -cd --no-tags -j2 ruby/platform/external/sfntly
repo sync -cd --no-tags -j2 ruby/platform/hardware/akm
repo sync -cd --no-tags -j2 ruby/platform/external/slf4j
repo sync -cd --no-tags -j2 ruby/platform/external/javassist
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/PackageInstaller
repo sync -cd --no-tags -j2 ruby/platform/external/mmc-utils
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvWalletCommon
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/time-services
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvEcoProvider
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gradle-plugin
repo sync -cd --no-tags -j2 ruby/platform/external/lz4
repo sync -cd --no-tags -j2 ruby/platform/external/libpng
repo sync -cd --no-tags -j2 ruby/platform/external/ceres-solver
repo sync -cd --no-tags -j2 ruby/device/generic/goldfish
repo sync -cd --no-tags -j2 ruby/platform/external/noto-fonts
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Camera
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/SnapdragonMusic
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Terminal
repo sync -cd --no-tags -j2 ruby/platform/external/pcre
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvSchedulePowerOnOff
repo sync -cd --no-tags -j2 ruby/platform/external/dbus-binding-generator
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvGuidePkgInstall
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Provision
repo sync -cd --no-tags -j2 ruby/platform/external/netperf
repo sync -cd --no-tags -j2 ruby/platform/external/xmlwriter
repo sync -cd --no-tags -j2 ruby/platform/external/drm_gralloc
repo sync -cd --no-tags -j2 ruby/device/letv
repo sync -cd --no-tags -j2 ruby/platform/frameworks/rs
repo sync -cd --no-tags -j2 ruby/platform/vendor/goodix/5208
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom/titanium_32
repo sync -cd --no-tags -j2 ruby/platform/external/libexif
repo sync -cd --no-tags -j2 msm8996/AMSS/common
repo sync -cd --no-tags -j2 ruby/platform/packages/services/Car
repo sync -cd --no-tags -j2 ruby/platform/external/owasp/sanitizer
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/net/wifi
repo sync -cd --no-tags -j2 ruby/platform/external/fsck_msdos
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/proprietary/mediascanner_plugin
repo sync -cd --no-tags -j2 msm8996/AMSS/modem_proc
repo sync -cd --no-tags -j2 ruby/platform/external/apache-http
repo sync -cd --no-tags -j2 ruby/platform/external/ImageMagick
repo sync -cd --no-tags -j2 ruby/platform/sdk
repo sync -cd --no-tags -j2 ruby/platform/hardware/broadcom/wlan
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/Contacts
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom-opensource/data-ipa-cfg-mgr
repo sync -cd --no-tags -j2 ruby/platform/external/apache-xml
repo sync -cd --no-tags -j2 ruby/platform/external/json-c
repo sync -cd --no-tags -j2 ruby/platform/external/ant-wireless/ant_native
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/python/linux-x86/2.7.5
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Bluetooth
repo sync -cd --no-tags -j2 ruby/platform/external/fdlibm
repo sync -cd --no-tags -j2 ruby/platform/external/v8
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/packages/NfcNxp/EseSpi
repo sync -cd --no-tags -j2 ruby/platform/external/libcap-ng
repo sync -cd --no-tags -j2 ruby/platform/external/touchsense
repo sync -cd --no-tags -j2 ruby/toolchain/binutils
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvAccount
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Test/connectivity
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/inputconnectioncommon
repo sync -cd --no-tags -j2 ruby/platform/external/smali
repo sync -cd --no-tags -j2 ruby/platform/external/safe-iop
repo sync -cd --no-tags -j2 ruby/platform/ndk
repo sync -cd --no-tags -j2 msm8996/AMSS/build
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/BugPostbox
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/providers/DownloadProvider
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom/thulium
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvTheme
repo sync -cd --no-tags -j2 ruby/platform/system/keymaster
repo sync -cd --no-tags -j2 ruby/platform/external/conscrypt
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/irchipd
repo sync -cd --no-tags -j2 ruby/platform/external/svox
repo sync -cd --no-tags -j2 ruby/platform/external/jdiff
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvSuperManager
repo sync -cd --no-tags -j2 ruby/platform/external/glide
repo sync -cd --no-tags -j2 ruby/platform/frameworks/opt/net/ethernet
repo sync -cd --no-tags -j2 leui_lollipop/platform/packages/apps/LetvCameraPrototype
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvTelephonyExtraServices
repo sync -cd --no-tags -j2 ruby/platform/external/ppp
repo sync -cd --no-tags -j2 ruby/device/qcom/sepolicy
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/Messaging
repo sync -cd --no-tags -j2 ruby/platform/external/bsdiff
repo sync -cd --no-tags -j2 ruby/platform/external/sonic
repo sync -cd --no-tags -j2 ruby/platform/build/blueprint
repo sync -cd --no-tags -j2 ruby/platform/external/fonttools
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/misc
repo sync -cd --no-tags -j2 letv/platform/external/chromium-webview
repo sync -cd --no-tags -j2 ruby/platform/system/vold
repo sync -cd --no-tags -j2 ruby/platform/external/apache-commons-math
repo sync -cd --no-tags -j2 msm8996/AMSS/slpi_proc
repo sync -cd --no-tags -j2 ruby/platform/external/fec
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/CarrierConfig
repo sync -cd --no-tags -j2 ruby/platform/external/mtpd
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/preloadapps/others
repo sync -cd --no-tags -j2 ruby/platform/external/neven
repo sync -cd --no-tags -j2 ruby/platform/vendor/codeaurora/telephony
repo sync -cd --no-tags -j2 ruby/platform/external/jemalloc
repo sync -cd --no-tags -j2 ruby/platform/hardware/qcom/audio
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvVideoPlayer2
repo sync -cd --no-tags -j2 ruby/platform/external/droiddriver
repo sync -cd --no-tags -j2 ruby/platform/vendor/letv/proprietary/msto
repo sync -cd --no-tags -j2 ruby/platform/external/dagger2
repo sync -cd --no-tags -j2 ruby/platform/external/rmi4utils
repo sync -cd --no-tags -j2 ruby/platform/external/pdfium
repo sync -cd --no-tags -j2 leui_lollipop/platform/vendor/letv/packages/LetvDocumentsUI
repo sync -cd --no-tags -j2 ruby/platform/prebuilts/ndk
repo sync -cd --no-tags -j2 ruby/platform/external/apache-harmony
repo sync -cd --no-tags -j2 ruby/platform/external/gptfdisk
repo sync -cd --no-tags -j2 ruby/device/sample
repo sync -cd --no-tags -j2 ruby/platform/vendor/qcom/titanium_64
repo sync -cd --no-tags -j2 msm8996/AMSS/rpm_proc
repo sync -cd --no-tags -j2 ruby/platform/external/libyuv
repo sync -cd --no-tags -j2 ruby/platform/hardware/libhardware_legacy
repo sync -cd --no-tags -j2 ruby/platform/external/e2fsprogs
repo sync -cd --no-tags -j2 ruby/platform/hardware/broadcom/libbt
repo sync -cd --no-tags -j2 ruby/platform/external/opencv3
repo sync -cd --no-tags -j2 ruby/device/generic/common
repo sync -cd --no-tags -j2 ruby/platform/external/cmockery
repo sync -cd --no-tags -j2 msm8996/AMSS/boot_images
repo sync -cd --no-tags -j2 ruby/platform/external/vixl
repo sync -cd --no-tags -j2 ruby/platform/external/libcxxabi
repo sync -cd --no-tags -j2 ruby/platform/external/llvm
repo sync -cd --no-tags -j2 letv/platform/vendor/letv/packages/LetvZxing
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/SoundRecorder
repo sync -cd --no-tags -j2 ruby/platform/system/nativepower
repo sync -cd --no-tags -j2 ruby/platform/packages/apps/TvSettings
